//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int MoneyTransfered { get; set; }
        public int TransferType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
