//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSTest.PersonDetailsApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonFile
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public bool IsActive { get; set; }
        public int PersonId { get; set; }
    
        public virtual PersonDetail PersonDetail { get; set; }
    }
}
